name: build-docker

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download env
        uses: subekti404dev/urvault-action@v1
        with:
          baseurl: ${{ secrets.URVAULT_URL }}
          token: ${{ secrets.URVAULT_TOKEN }}
          id: m8jc2d8r53
          filename: env.json
          type: json

      - run: cat env.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: "${{ vars.DOCKER_TAGS }}"
