name: build-docker

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download env
        uses: subekti404dev/urvault-action@v1
        with:
          secret: ${{ secrets.URVAULT_SECRET }}
          filename: env.json
          type: json

      - run: cat env.json

      - name: Docker Build
        uses: subekti404dev/docker-build-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}\
          platforms: linux/amd64,linux/arm64
          tags: "${{ vars.DOCKER_TAGS }}"
