name: build-docker

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download env
        uses: subekti404dev/github-action-urvault@v1
        with:
          baseurl: ${{ secrets.URVAULT_URL }}
          token: ${{ secrets.URVAULT_TOKEN }}
          id: m8jc2d8r53
          filename: .env
          type: dotenv

      - name: Set Environment Variables
        id: set-env
        run: |
          while IFS= read -r line || [[ -n "$line" ]]; do
            echo "$line" >> $GITHUB_ENV
          done < .env

      - name: Debug Environment Variables
        run: |
          echo "DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN=${{ env.DOCKERHUB_TOKEN }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: "${{ vars.DOCKER_TAGS }}"
